### ISSUE TITLE
this is a method :)

### ISSUE THREAD

**Issue by typemytype** [robofont-mechanic/mechanic-2#13]
see https://github.com/robofont-mechanic/mechanic-2/blob/036e6b015ff22786a817fcc2f57c5244e81dd8d4/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py#L186

```Could not download the extension zip file for: '<bound method BaseExtensionItem.extensionName of <mechanic2.extensionItem.ExtensionYamlItem object at 0x1199f1240>>```

**Comment by gferreira** [comment]
should be fixed in #14
