### ISSUE TITLE
sort ext to update to the top of the list...

### ISSUE THREAD

**Issue by typemytype** [robofont-mechanic/mechanic-2#17]

**Comment by verbosus** [comment]
On top of sorting extensions that need updates to the top, I also added a bit of code to scroll the NSTextView to the top, so these become visible in 818cc3767c2808ee77a300cdeec6e23e3c447698

**Comment by verbosus** [comment]
Fixed in https://github.com/robofont-mechanic/mechanic-2/commit/bdaabe5473f3eadb1e13a8f138657765779f00d3

**Comment by verbosus** [comment]
@typemytype can you close?
