### ISSUE TITLE
Wait a while after checking for updates

### ISSUE THREAD

**Issue by LettError** [robofont-mechanic/mechanic-2#2]
If Check For Updates has run, Mechanic can store the datestamp and postpone asking again for a number of hours. If one happens to restart RoboFont frequently, it does not need to check every time.

**Comment by jackjennings** [comment]
Refence from previous implementation: https://github.com/robofont-mechanic/Mechanic/blob/master/src/lib/mechanic/update.py#L20

**Comment by jackjennings** [comment]
Interval was previously set to one hour (3600 seconds)

**Comment by LettError** [comment]
Enhancements:

* the buttons can say `Later` / `Now` rather than `No` / `Yes`.
* maybe while updating the progressbar can indicate where in the list of extensions it is. `7 of 15` or something like that. Obviously it can still take time, but at least we know it is doing something.
