### ISSUE TITLE
problem reading Extension Store json stream

### ISSUE THREAD

**Issue by gferreira** [robofont-mechanic/mechanic-2#30]
continuing from [Prepolator and MetricsMachine are not listed in Mechanic 2.0](https://forum.robofont.com/topic/868/prepolator-and-metricsmachine-are-not-listed-in-mechanic-2-0)

- extensions from the Extension Store do not appear in the list
- the [Extension Store json stream URL](https://extensionstore.robofont.com/data.json) appears to be correct
- the `robofont-3-py3.log` file contains the following error:

```console
20/05/2020 14:16:04 >    ERROR > Mechanic >> Cannot read url 'https://extensionstore.robofont.com/data.json'
20/05/2020 14:16:04 >    ERROR > Mechanic >> Error 'Error Domain=NSURLErrorDomain Code=-1200 "The operation couldn’t be completed. (NSURLErrorDomain error -1200.)" UserInfo=0x6000001a2760 {_kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9824, NSUnderlyingError=0x600000244080 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1200.)", NSErrorPeerCertificateChainKey=(
                                          >> ), NSErrorFailingURLKey=https://extensionstore.robofont.com/data.json, NSErrorFailingURLStringKey=https://extensionstore.robofont.com/data.json, NSErrorClientCertificateStateKey=0}'
```

I can’t reproduce it in RF3.3 or RF3.4 (10.13.6)

any idea what could be causing this error? thanks!

**Comment by gferreira** [comment]
the error is happening on macOS 10.10.5

**Comment by gferreira** [comment]
it seems the problem is related to SSL certificates and macOS 10.10 (?)

the name of error -1200 is `NSURLErrorSecureConnectionFailed`

[ATS and HTTPS Server Trust Evaluation Requirements](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW61) says:

> However, this fine-grained control is not available in older operating systems (iOS 10.0 and older, or macOS 10.12 and older). To maintain backward-compatibility when you use any of these keys, you must also set the value of the NSAllowsArbitraryLoads key to YES, taking advantage of its version-specific behavior. It works as follows:

**Comment by typemytype** [comment]
FYI: RF already has already NSAppTransportSecurity -> NSAllowsArbitraryLoads set to True...

**Comment by typemytype** [comment]
fixed by using an older version of mechanic as this seems to be a SSL certificate issue on 10.10

for 10.10 use https://github.com/robofont-mechanic/mechanic-2/tree/1901e663e1cc63c5485fa0cc05e9a423961560ee
