### ISSUE TITLE
Repositories with “main” branch

### ISSUE THREAD

**Issue by arialcrime** [robofont-mechanic/mechanic-2#33]
Due to the changes to [GitHub’s default branch behaviour](https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/) (and [Git in general](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/)), newly created extension repositories will have their primary branch called `main` instead of `master`.

Mechanic’s [urlFormatters](https://github.com/robofont-mechanic/mechanic-2/blob/f110f60abfbf6de07f11a64284a043a2598a553c/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py#L350) do not take this into account yet, so new extensions like [ScriptLauncher](https://github.com/mrecord/ScriptLauncher) causes the following traceback:

```
Traceback (most recent call last):
  File "/Users/benedikt/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 189, in _remoteInstallCallback
    with zipfile.ZipFile(io.BytesIO(data.bytes())) as z:
  File "zipfile.pyc", line 1225, in __init__
  File "zipfile.pyc", line 1292, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyObjCTools/AppHelper.pyc", line 89, in scheduleCallWithDelay_
  File "PyObjCTools/AppHelper.pyc", line 105, in performCall
  File "/Users/benedikt/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 195, in _remoteInstallCallback
    raise ExtensionRepoError(message)
mechanic2.mechanicTools.ExtensionRepoError: Could not extract the extension zip file for: 'ScriptLauncher'
```

**Comment by typemytype** [comment]
I see

is there a api link to the primary branch directly, whatever the name of that branch is?

**Comment by typemytype** [comment]
maybe this works:

as a direct download of the zip without specifying a branch

`https://api.github.com/repos/mrecord/ScriptLauncher/zipball`

needs to see if this works without a browser, by some code

**Comment by typemytype** [comment]
could you test out Mechanic from source?

before I touch the version number, before Mechanic picks it up :)

**Comment by arialcrime** [comment]
Oh nice, thanks for the quick fix! 🚀
I can confirm that the new version works without any problems at my end.

**Comment by typemytype** [comment]
I like rockets!
