### ISSUE TITLE
It looks like the links to the documentation are broken..

### ISSUE THREAD

**Issue by typedev** [robofont-mechanic/mechanic-2#35]
It looks like the links to the documentation are broken..

**Comment by typemytype** [comment]
could you clarify which links?

are you referring to the documentation links of an extension? 

double click an extension in the Mechanic windows brings you to the root of the repository

**Comment by typedev** [comment]
I apologize for what I wrote is not clear .. 
links from the README.md file on this page (https://github.com/robofont-mechanic/mechanic-2) lead to the site robofont.com 404

**Comment by typemytype** [comment]
oh yeah, off course thanks :)
