### ISSUE TITLE
Clicking on the area just before the name of any extension makes RF crash. 100% reproducible

### ISSUE THREAD

**Issue by gitdaria** [robofont-mechanic/mechanic-2#36]
See attachments.
Version 4.1b (build 2110011334)
Mac OS 11.6 (20G165)

https://user-images.githubusercontent.com/92150595/136522902-0f2da93a-ee75-4c9c-b563-57ff3cec664d.mov
[Dont click.txt](https://github.com/robofont-mechanic/mechanic-2/files/7309620/Dont.click.txt)
![Screenshot 2021-10-07 at 14 41 16](https://user-images.githubusercontent.com/92150595/136522987-f4b79694-86e6-4ebb-967d-a7ba7a8b5f97.png)

**Comment by typemytype** [comment]
are you sure you have the latest version of Mechanic?

this is a direct download link --> https://github.com/robofont-mechanic/mechanic-2/archive/refs/heads/master.zip

**Comment by gitdaria** [comment]
I was quite sure, but to be surer I just reinstalled it. Same :(

**Comment by arialcrime** [comment]
I can reproduce this in Mac OS 10.14.6 with Version 4.1b (build 2110061420). Here are the the most recent entries from the log after the crash:

```
07/10/2021 14:51:16 >   OUTPUT > ROBOFONT >> Traceback (most recent call last):
07/10/2021 14:51:16 >   OUTPUT > ROBOFONT >> File "/Applications/Robofont4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaList.py", line 183, in tableView_objectValueForTableColumn_row_
07/10/2021 14:51:16 >   OUTPUT > ROBOFONT >> return getattr(item, columnID)()
07/10/2021 14:51:16 >   OUTPUT > ROBOFONT >> TypeError
07/10/2021 14:51:16 >   OUTPUT > ROBOFONT >> :
07/10/2021 14:51:16 >   OUTPUT > ROBOFONT >> 'NSKVONotifying_MCExtensionListItem' object is not callable
```

Hope this helps!

**Comment by typemytype** [comment]
fixed
