### ISSUE TITLE
Alphabetical sorting is case-sensitive

### ISSUE THREAD

**Issue by nicksherman** [robofont-mechanic/mechanic-2#50]
I recently was looking for the showDist extension in Mechanic, and was somewhat surprised to not find it there. After asking @frankrolf about it, I learned the extension is indeed available there, but shows up at the end of the list because its name starts with a lowercase s instead of an uppercase S. This seems unintuitive – the sorting probably should not be case sensitive.

**Comment by typemytype** [comment]
I guess this could be solved with case insensitive order of extensions in the api json


https://github.com/robofont-mechanic/mechanic-2-server/blob/d073072cc8a03c387256d115dce78f9d9d449d4b/api/v2/registry.json#L10C21-L10C31
https://robofontmechanic.com/api/v2/registry.json

**Comment by typemytype** [comment]
should be fixed here: https://github.com/robofont-mechanic/mechanic-2-server/commit/10659d935beb53b3470289ef6ef4fd869907ab55
