### ISSUE TITLE
requirements error

### ISSUE THREAD

**Issue by tetris-hermetris** [robofont-mechanic/mechanic-2#7]
printed that in output, when try to launch it:

> Traceback (most recent call last):
>   File "main.py", line 2, in <module>
>   File "/Users/max/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 13, in <module>
>   File "/Users/max/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/settings.py", line 4, in <module>
> ModuleNotFoundError: No module named 'yaml'

After installing PyYAML via pip, everything works fine

**Comment by typemytype** [comment]
yaml has to be embedded into the next version of RoboFont (a release is coming)

a local install will also work

**Comment by typemytype** [comment]
RF3.1 is released and will resolve this issue

thanks
