### ISSUE TITLE
your time “checked at” seems to report a different timezone

### ISSUE THREAD

**Issue by typemytype** [robofont-mechanic/mechanic-2#8]
I guess there is no time zone at all

**Comment by verbosus** [comment]
I can’t reproduce this on the latest Mechanic. I think @typemytype fixed it in 0ad57cbffe95b8ccde7a43c653aac18fdeaa8daf

**Comment by typemytype** [comment]
this is idd fixed in https://github.com/robofont-mechanic/mechanic-2/commit/0ad57cbffe95b8ccde7a43c653aac18fdeaa8daf

**Comment by verbosus** [comment]
idd! 😜
